version: '3.8'

services:
  dailySummaryEmail:
    image: git.tylerdavis.net/tyler/dailysummaryemail:latest # Or :latest-dev for alpha/beta/RC releases
    container_name: dailySummaryEmail
    platform: "linux/amd64"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
