name: Release on Push to Main Branch

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract version from version.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' version.json)
          DOCKER_TAG="${VERSION/v/}"
          DOCKER_TAG="${DOCKER_TAG/+/-}"
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "docker_tag=$DOCKER_TAG" >> $GITHUB_ENV
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      - name: Determine if Pre-release and Type
        id: prerelease_check
        run: |
          if [[ "${{ env.version }}" == *"-alpha"* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
            echo "pre_release_type=alpha" >> $GITHUB_ENV
          elif [[ "${{ env.version }}" == *"-beta"* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
            echo "pre_release_type=beta" >> $GITHUB_ENV
          elif [[ "${{ env.version }}" == *"-rc"* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
            echo "pre_release_type=rc" >> $GITHUB_ENV
          elif [[ "${{ env.version }}" =~ ^v0\..* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
            echo "pre_release_type=dev" >> $GITHUB_ENV
          else
            echo "pre_release=false" >> $GITHUB_ENV
            echo "pre_release_type=" >> $GITHUB_ENV
          fi

      - name: Get All Relevant Commit Messages for Release Notes
        id: commit_messages
        run: |
          LAST_STABLE_TAG=$(git tag -l | grep -E '^v[0-9]+(\.[0-9]+)*$' | sort -V | tail -1)
          echo "Last stable tag: $LAST_STABLE_TAG"
          git log "$LAST_STABLE_TAG"..HEAD --pretty=format:"* %h: %s (by %an)" | sed 's/[$&`"'\''\\\/]/\\&/g' | sed ':a;N;$!ba;s/\n/#NEWLINE#/g' > sanitized_commits.txt

      - name: Prepare Release Notes
        run: |
          SANITIZED_COMMITS=$(< sanitized_commits.txt)
          SANITIZED_COMMITS_WITH_NEWLINES=$(echo "$SANITIZED_COMMITS" | sed 's/#NEWLINE#/\n/g')
          {
            echo "Automated release of version ${{ env.version }}"
            echo ""
            echo "### Commits in this release:"
            echo "$SANITIZED_COMMITS_WITH_NEWLINES"
          } > release_body.txt

      - name: Create Forgejo Release
        run: |
          BODY=$(cat release_body.txt)
          PRE_RELEASE=${{ env.pre_release }}
          curl -s -X POST "${{ env.FORGEJO_URL }}/api/v1/repos/${{ github.repository }}/releases" \
            -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"tag_name\": \"${{ env.version }}\",
              \"name\": \"${{ env.version }}\",
              \"body\": $(echo "$BODY" | jq -Rs .),
              \"draft\": false,
              \"prerelease\": $PRE_RELEASE
            }"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PAT }}

      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.FORGEJO_REGISTRY }}
          username: ${{ secrets.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ env.repo_name }}:${{ env.docker_tag }} \
            -t ghcr.io/${{ env.repo_name }}:latest-dev \
            -t ${{ secrets.FORGEJO_REGISTRY }}/${{ env.repo_name }}:${{ env.docker_tag }} \
            -t ${{ secrets.FORGEJO_REGISTRY }}/${{ env.repo_name }}:latest-dev \
            .

      - name: Push to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.repo_name }}:${{ env.docker_tag }}
          docker push ghcr.io/${{ env.repo_name }}:latest-dev

      - name: Push to Forgejo Container Registry
        run: |
          docker push ${{ secrets.FORGEJO_REGISTRY }}/${{ env.repo_name }}:${{ env.docker_tag }}
          docker push ${{ secrets.FORGEJO_REGISTRY }}/${{ env.repo_name }}:latest-dev

      - name: Tag and Push Latest for Stable Releases
        if: ${{ env.pre_release == 'false' }}
        run: |
          # GHCR
          docker tag ghcr.io/${{ env.repo_name }}:${{ env.docker_tag }} ghcr.io/${{ env.repo_name }}:latest
          docker push ghcr.io/${{ env.repo_name }}:latest

          # Forgejo
          docker tag ${{ secrets.FORGEJO_REGISTRY }}/${{ env.repo_name }}:${{ env.docker_tag }} ${{ secrets.FORGEJO_REGISTRY }}/${{ env.repo_name }}:latest
          docker push ${{ secrets.FORGEJO_REGISTRY }}/${{ env.repo_name }}:latest