name: Release on Push to Main Branch

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
      - dev   # Trigger on pushes to the dev branch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      version: v1.3.0-beta.31
      docker_tag: 1.3.0-beta.31
      repo_name: tdavis6/dailysummaryemail
      pre_release: true
      pre_release_type: beta

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Extract version from version.json
        id: get_version
        run: |
          # Extract the original version and prepare a Docker-compatible tag
          VERSION=$(jq -r '.version' version.json)
          DOCKER_TAG=$(echo "$VERSION" | sed 's/^v//' | sed 's/+/-/g')
          # Convert repository name to lowercase for Docker compatibility
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "docker_tag=$DOCKER_TAG" >> $GITHUB_ENV
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      - name: Determine if Pre-release and Type
        id: prerelease_check
        run: |
          # Check if the version is a pre-release and determine type
          if [[ "${{ env.version }}" == *"-alpha"* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
            echo "pre_release_type=alpha" >> $GITHUB_ENV
          elif [[ "${{ env.version }}" == *"-beta"* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
            echo "pre_release_type=beta" >> $GITHUB_ENV
          elif [[ "${{ env.version }}" == *"-rc"* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
            echo "pre_release_type=rc" >> $GITHUB_ENV
          elif [[ "${{ env.version }}" =~ ^v0\..* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
            echo "pre_release_type=dev" >> $GITHUB_ENV
          else
            echo "pre_release=false" >> $GITHUB_ENV
            echo "pre_release_type=" >> $GITHUB_ENV
          fi

      - name: Get All Relevant Commit Messages for Release Notes
        id: commit_messages
        run: |
          # Find the last stable (non-pre-release) tag
          LAST_STABLE_TAG=$(git tag -l | grep -E '^v[0-9]+(\.[0-9]+)*$' | sort -V | tail -1)
          
          # Get all commit messages since the last stable tag
          COMMITS=$(git log "$LAST_STABLE_TAG"..HEAD --pretty=format:"* %h: %s")

          # Debug: Check if the COMMITS variable has content
          echo "$COMMITS"  # This will help you ensure that commit data is being fetched

          # Check if COMMITS is non-empty before running sed
          if [ -n "$COMMITS" ]; then
            # Sanitize commit messages to escape special characters using printf
            COMMITS=$(printf "%s" "$COMMITS" | sed -E \
              's/[&]/\\&/g' \
              -e 's/\\/\\\\/g' \
              -e 's/`/\\`/g' \
              -e 's/\*/\\*/g' \
              -e 's/"/\\"/g' \
              -e 's/\$/\\\$/g' \
              -e 's/\(/\\(/g' \
              -e 's/\)/\\)/g' \
              -e 's/\[/\\[/g' \
              -e 's/\]/\\]/g' \
              -e 's/\|/\\|/g' \
              -e 's/\{/\\\{/g' \
              -e 's/\}/\\\}/g')
          else
            echo "No commits found since the last stable tag."
            COMMITS="No commits since the last stable tag."
          fi

          # Remove duplicate commit messages while keeping their commit hashes
          COMMITS=$(echo "$COMMITS" | sort | uniq)

          # Output the final sanitized commit messages for the release notes
          echo "commits=${COMMITS}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          prerelease: ${{ env.pre_release }}  # Use pre_release determined from the version
          body: |
            Automated release of version ${{ env.version }}

            ### Commits in this release:
            ${{ env.commits }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Build and Push Docker Image
        run: |
          # Build the Docker image with the version-specific tag
          docker build -t ghcr.io/${{ env.repo_name }}:${{ env.docker_tag }} .
          
          # Apply the latest-dev tag for all releases, regardless of stability
          docker tag ghcr.io/${{ env.repo_name }}:${{ env.docker_tag }} ghcr.io/${{ env.repo_name }}:latest-dev

          # Push both tags to the GitHub Container Registry
          docker push ghcr.io/${{ env.repo_name }}:${{ env.docker_tag }}
          docker push ghcr.io/${{ env.repo_name }}:latest-dev
