name: Release on Push to Release Branch

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from version.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' version.json | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Determine if Pre-release
        id: prerelease_check
        run: |
          if [[ "${{ env.version }}" == *"-alpha"* || "${{ env.version }}" == *"-beta"* || "${{ env.version }}" =~ ^0\..* ]]; then
            echo "pre_release=true" >> $GITHUB_ENV
          else
            echo "pre_release=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          prerelease: ${{ env.pre_release }}
          body: "Automated release of version ${{ env.version }}"
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.version }} .
          docker push ghcr.io/${{ github.repository }}:${{ env.version }}
